version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: bayeta-mongo
    ports:
      - "27017:27017"
    networks:
      - bayeta-network

  app:
    build: .
    container_name: bayeta-app
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
    networks:
      - bayeta-network

networks:
  bayeta-network:
    driver: bridge
